version: '2.4'
services:
  smstools:
    build: 
      context: .
      target: smstools
    volumes:
      - sms:/var/spool/sms
      - ./config:/home/gateway/.config/smsgateway/
    environment:
      CONFIG_DIR: "/home/gateway/.config/smsgateway"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    stop_grace_period: 30s
    restart: unless-stopped

  telegram:
    build:
      context: .
      target: smsgateway
    environment:
      CONFIG_DIR: "/home/gateway/.config/smsgateway"
    volumes:
      - sms:/var/spool/sms
      - ./config:/home/gateway/.config/smsgateway/
    entrypoint: ['python3', '-m', 'smsgateway.sources.telegram']

    depends_on:
      - smstools
    restart: unless-stopped
    stop_grace_period: 30s

  matrix:
    build:
      context: .
      target: smsgateway
    environment:
      - CONFIG_DIR
    volumes:
      - ../smsgateway:/usr/local/lib/python3.9/site-packages/smsgateway:ro
      - sms:/var/spool/sms
      - ./config:$CONFIG_DIR
    working_dir: "/etc/smsgateway"
    entrypoint: ['python3', '-m', 'smsgateway.sources.matrix']

    depends_on:
      - smstools
    restart: unless-stopped
    stop_grace_period: 30s
    
volumes:
  sms:
    driver_opts:
      type: tmpfs
      device: tmpfs
      #size: '67108864' # 64M
